/*
 * Copyright (c) 2026 The GoPlus Authors (goplus.org). All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ixgo

import (
	"go/types"
	"reflect"

	"golang.org/x/tools/go/ssa"
)

// DirectCallContext gives a generated direct-call adapter access to the
// current call's arguments and result register.
type DirectCallContext struct {
	frame  *frame
	result register
	args   []register
}

// DirectCallArg returns the argument at index using its generated static type.
// A nil interface value is converted to the zero value of T.
func DirectCallArg[T any](ctx DirectCallContext, index int) T {
	v := ctx.frame.reg(ctx.args[index])
	if v == nil {
		var zero T
		return zero
	}
	return v.(T)
}

// SetResult stores the result produced by a generated direct-call adapter.
func (ctx DirectCallContext) SetResult(result any) {
	ctx.frame.setReg(ctx.result, result)
}

// DirectCallAdapter is a qexp-generated, reflection-free call adapter.
type DirectCallAdapter func(DirectCallContext)

// DirectCallBinding binds an exact package function or method to its generated
// adapter. Bindings are generated by qexp; Target must be the package-level
// function or method expression invoked by Adapter.
type DirectCallBinding struct {
	Target  reflect.Value
	Adapter DirectCallAdapter
}

func (binding DirectCallBinding) valid() bool {
	return binding.Adapter != nil && binding.Target.IsValid() &&
		binding.Target.Kind() == reflect.Func && !binding.Target.IsNil()
}

func (binding DirectCallBinding) matchesTarget(resolved reflect.Value, expected reflect.Type) bool {
	if !resolved.IsValid() || binding.Target.Type() != expected || resolved.Type() != expected {
		return false
	}
	// MethodByName may return a reflect.Value with different internal flags from
	// reflect.ValueOf the same qexp-generated method expression.
	return binding.Target == resolved || binding.Target.Pointer() == resolved.Pointer()
}

func directCallSignature(fn *ssa.Function) *types.Signature {
	sig := fn.Signature
	if sig.Recv() != nil {
		sig = wrapMethodType(sig)
	}
	return sig
}

func directCallType(interp *Interp, fn *ssa.Function) reflect.Type {
	return interp.preToType(directCallSignature(fn))
}

func directCallKey(fn *ssa.Function) string {
	if obj, ok := fn.Object().(*types.Func); ok {
		return obj.FullName()
	}
	return fn.String()
}

func directCallPackagePath(fn *ssa.Function) string {
	if fn.Pkg != nil && fn.Pkg.Pkg != nil {
		return fn.Pkg.Pkg.Path()
	}
	if obj, ok := fn.Object().(*types.Func); ok && obj.Pkg() != nil {
		return obj.Pkg().Path()
	}
	return ""
}

// directCallMethodKey must match the key format generated by
// cmd/internal/export/direct_call.go.
func directCallMethodKey(typ reflect.Type, method string) (pkgPath, key string, ok bool) {
	ptr := typ.Kind() == reflect.Ptr
	if ptr {
		typ = typ.Elem()
	}
	if typ.Name() == "" || typ.PkgPath() == "" {
		return "", "", false
	}
	pkgPath = typ.PkgPath()
	receiver := pkgPath + "." + typ.Name()
	if ptr {
		receiver = "*" + receiver
	}
	return pkgPath, "(" + receiver + ")." + method, true
}

func lookupDirectCallBinding(interp *Interp, pkgPath, key string) (DirectCallBinding, bool) {
	bindings, ok := interp.directCalls[pkgPath]
	if !ok {
		return DirectCallBinding{}, false
	}
	binding, ok := bindings[key]
	if !ok || !binding.valid() {
		return DirectCallBinding{}, false
	}
	return binding, true
}

// snapshotDirectCallBindings captures the Loader's installed package view at
// interpreter construction time. Package registration is setup-only: later
// registry changes neither race with invoke resolution nor invalidate cached
// callsites.
func snapshotDirectCallBindings(loader Loader, prog *ssa.Program) map[string]map[string]DirectCallBinding {
	paths := make(map[string]struct{})
	if prog != nil {
		for _, pkg := range prog.AllPackages() {
			if pkg != nil && pkg.Pkg != nil {
				paths[pkg.Pkg.Path()] = struct{}{}
			}
		}
	}
	for _, pkg := range loader.Packages() {
		if pkg != nil {
			paths[pkg.Path()] = struct{}{}
		}
	}

	snapshot := make(map[string]map[string]DirectCallBinding)
	for path := range paths {
		pkg, ok := loader.Installed(path)
		if !ok || len(pkg.DirectCalls) == 0 {
			continue
		}
		bindings := make(map[string]DirectCallBinding, len(pkg.DirectCalls))
		for key, binding := range pkg.DirectCalls {
			bindings[key] = binding
		}
		snapshot[path] = bindings
	}
	return snapshot
}

func resolveStaticDirectCall(interp *Interp, fn *ssa.Function, resolved reflect.Value) (DirectCallAdapter, bool) {
	pkgPath := directCallPackagePath(fn)
	key := directCallKey(fn)
	if _, overridden := interp.ctx.override[key]; overridden {
		return nil, false
	}
	if _, overridden := lookupExternal(key); overridden {
		return nil, false
	}
	binding, ok := lookupDirectCallBinding(interp, pkgPath, key)
	if !ok {
		return nil, false
	}
	if expected := directCallType(interp, fn); !binding.matchesTarget(resolved, expected) {
		return nil, false
	}
	return binding.Adapter, true
}

func makeStaticDirectCallInstr(interp *Interp, fn *ssa.Function, resolved reflect.Value, result register, args []register) func(*frame) {
	adapter, ok := resolveStaticDirectCall(interp, fn, resolved)
	if !ok {
		return nil
	}
	return func(fr *frame) {
		interp.invokeDirectCall(fr, adapter, result, args)
	}
}

func (i *Interp) invokeDirectCall(fr *frame, adapter DirectCallAdapter, result register, args []register) {
	i.trackDeferFrame(fr)
	adapter(DirectCallContext{frame: fr, result: result, args: args})
}

func (i *Interp) trackDeferFrame(fr *frame) {
	if fr.deferid != 0 {
		i.deferMap.Store(fr.deferid, fr)
	}
}
